global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'minio-cluster'
    metrics_path: '/minio/v2/metrics/cluster'
    file_sd_configs:
      - files:
        - /etc/prometheus/targets_minio.json

  - job_name: 'host-devices'
    metrics_path: '/metrics' # Default for node_exporter
    file_sd_configs:
      - files:
        - /etc/prometheus/targets_node.json
